apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feeds
  labels:
    app: udagram-api-feeds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-api-feeds
  template:
    metadata:
      labels:
        app: udagram-api-feeds
    spec:
      containers:
        - name: udagram-api-feeds
          image: xthian82/udagram-api-feeds
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-feeds
  name: udagram-api-feeds-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: udagram-api-feeds
