apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: udagram-api-feeds-memory-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: udagram-api-feeds
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageValue: 0.5Gi
